services:
  server:
    build:
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - go_modules:/go/pkg/mod
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - DB_HOST=postgres
    command: >
      sh -c "air -c .air.toml || air --build.cmd 'go build -o ./tmp/main ./cmd/api' --build.bin './tmp/main'"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env

  postgres:
    image: postgres:18
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  go_modules: